// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxE-8HiyOqrRFUJ5OYUbNPUc0LVn7z4iU',
    appId: '1:503674439315:web:d0a2ec6972bbe9b8d3ef66',
    messagingSenderId: '503674439315',
    projectId: 'reserva-de-arma-6c777',
    authDomain: 'reserva-de-arma-6c777.firebaseapp.com',
    storageBucket: 'reserva-de-arma-6c777.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3FWYU9iZyvth9CC2gvpUhz5A8lFQEwmw',
    appId: '1:503674439315:android:8cf2bc30d0bc20b0d3ef66',
    messagingSenderId: '503674439315',
    projectId: 'reserva-de-arma-6c777',
    storageBucket: 'reserva-de-arma-6c777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYSB0xUK10MoffqZAw3j6G6dw60WnzK5A',
    appId: '1:503674439315:ios:da7901958cf15bb2d3ef66',
    messagingSenderId: '503674439315',
    projectId: 'reserva-de-arma-6c777',
    storageBucket: 'reserva-de-arma-6c777.firebasestorage.app',
    iosBundleId: 'com.example.reservaDeArma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYSB0xUK10MoffqZAw3j6G6dw60WnzK5A',
    appId: '1:503674439315:ios:da7901958cf15bb2d3ef66',
    messagingSenderId: '503674439315',
    projectId: 'reserva-de-arma-6c777',
    storageBucket: 'reserva-de-arma-6c777.firebasestorage.app',
    iosBundleId: 'com.example.reservaDeArma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxE-8HiyOqrRFUJ5OYUbNPUc0LVn7z4iU',
    appId: '1:503674439315:web:33c55f22fa95edc4d3ef66',
    messagingSenderId: '503674439315',
    projectId: 'reserva-de-arma-6c777',
    authDomain: 'reserva-de-arma-6c777.firebaseapp.com',
    storageBucket: 'reserva-de-arma-6c777.firebasestorage.app',
  );
}
